### ISSUE TITLE
Bug: /scan on Dep-scan server returns the SBOM

### ISSUE THREAD

**Issue by Forgh** [owasp-dep-scan/dep-scan#384]
### Expected Behavior

DepScan server should return a scan report based on the given SBOM 
[SBOM.json](https://github.com/user-attachments/files/18349535/SBOM.json)

### Actual Behavior

While running depscan and cdxgen in server mode, any SBOM (created by the very same version of CDXgen) sent to depscan server simply returns the SBOM I've sent.

[app.vdr.json](https://github.com/user-attachments/files/18349549/app.vdr.json)

### Steps to Reproduce

Using this docker-compose.yml (based on the README.md):

```yaml
version: '3.7'

services:
  cdxgen:
    image: ghcr.io/cyclonedx/cdxgen:latest
    ports:
      - "9090:9090"
    volumes:
      - /home/applications/owasp-depscan/data/mnt/work:/app # Set this to your directory containing sources
      - /home/applications/owasp-depscan/data/tmp:/tmp
    entrypoint: node /opt/cdxgen/bin/cdxgen.js --server --server-host 0.0.0.0 --server-port 9090

  depscan:
    image: ghcr.io/owasp-dep-scan/depscan:v5.5.0
    ports:
      - "7070:7070"
    volumes:
      - /home/applications/owasp-depscan/data/mnt/work:/app # Set this to your directory containing sources
      - /home/applications/owasp-depscan/data/tmp:/tmp
    entrypoint: depscan --server --server-host 0.0.0.0 --server-port 7070 --cdxgen-server http://cdxgen:9090
    environment:
      VDB_HOME: /app/vdb
    links:
      - "cdxgen:cdxgen"
```

```shell
docker-compose up -d
```
```shell
curl -X POST "hostname:7070/scan?type=npm" -H "Content-Type: multipart/form-data" -F "file=@./SBOM.json" o app.vdr.json
```
Here's the supplied SBOM.json file:
[SBOM.json](https://github.com/user-attachments/files/18349502/SBOM.json)

And here's the result: 
[app.vdr.json](https://github.com/user-attachments/files/18349549/app.vdr.json)

### Additional Information

Experienced the same behaviour with :
- depscan image build from the current commit on master (f350f0c3ff5d1d5e7cea3a2d74c34afdd0965424)
- ghcr.io/owasp-dep-scan/depscan:release-6.x
- ghcr.io/owasp-dep-scan/depscan:v5.5.0

/cache route has been called everytime I re-up'd one of these images

Response times can be really slow (up to 3-4 minutes)

Projects I've used the scanner on are pretty simple : 
- One npm project with just a lodash dependency
  - [package-lock.json](https://github.com/user-attachments/files/18349566/package-lock.json)
- The other is a conan + CMake project with a fmt dependecy
  - [conanfile.txt](https://github.com/user-attachments/files/18349584/conanfile.txt)

Using the scanner directly in my  GitLab CI pipeline with the v5.5.0 and the exact same projects produced empty reports;

```yaml
depscan:
  stage: security
  image: 
    name: ghcr.io/owasp-dep-scan/depscan:v5.5.0
    entrypoint: [""]
  script:
    - depscan --src ${CI_PROJECT_DIR} --reports-dir reports/ -t "conan,npm"
  artifacts:  
    paths:
      - reports/
```
depscan.pdf:
![image](https://github.com/user-attachments/assets/1f7abf98-5135-465e-a55c-93e2e13ab3f1)
[depscan-conan.json](https://github.com/user-attachments/files/18349672/depscan-conan.json)
[depscan-npm.json](https://github.com/user-attachments/files/18349673/depscan-npm.json)
[sbom-conan.json](https://github.com/user-attachments/files/18349674/sbom-conan.json)
[sbom-npm.json](https://github.com/user-attachments/files/18349676/sbom-npm.json)
